[colors]
ansi = [
    "#15161e",
    "#f7768e",
    "#9ece6a",
    "#e0af68",
    "#7aa2f7",
    "#bb9af7",
    "#7dcfff",
    "#a9b1d6",
]
background = "#1a1b26"
brights = [
    "#414868",
    "#f7768e",
    "#9ece6a",
    "#e0af68",
    "#7aa2f7",
    "#bb9af7",
    "#7dcfff",
    "#c0caf5",
]
compose_cursor = "#c0caf5"
cursor_bg = "#c0caf5"
cursor_border = "#c0caf5"
cursor_fg = "#1a1b26"
foreground = "#c0caf5"
scrollbar_thumb = "#283457"
selection_bg = "#283457"
selection_fg = "#c0caf5"
split = "#414868"
visual_bell = "#15161e"

[colors.indexed]
16 = "#bb9af7"
17 = "#c0caf5"

[colors.tab_bar]
background = "#171822"
inactive_tab_edge = "#283457"

[colors.tab_bar.active_tab]
bg_color = "#7aa2f7"
fg_color = "#16161e"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab]
bg_color = "#181924"
fg_color = "#c0caf5"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#1a1b26"
fg_color = "#c0caf5"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab]
bg_color = "#283457"
fg_color = "#c0caf5"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab_hover]
bg_color = "#414868"
fg_color = "#c0caf5"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[metadata]
author = "Noctalia"
name = "Noctalia"
